FILENAME=spisd.device
DIR=build-device-debug
OBJECTS=device.o spi-par.o spi-par-low.o sd.o disk-int.o timer.o

SRCDIRS=.
INCDIRS=.

EXTRA_CFLAGS=-ramiga-dev -DDEBUG=1
EXTRA_LDFLAGS=-ldebug

include common.mk
